[project]
name = "zvyn-rpi-ws281x-demo"
version = "0.1.0"
description = "Let the LEDs blink!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rpi-ws281x>=5.0.0",
]

[tool.ruff.lint]
select = ["E", "F", "PIE", "UP", "B", "SIM", "I"]
